config/routes.rb
HamsterEntries::Application.routes.draw do
  devise_for :users, path_names: { sign_in: "login", sign_up: "login"},
    controllers: {registrations: "registrations", sessions: "sessions"}

  resources :shows
  root to: "dashboards#show"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show

  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :add_cookie_acceptance, only: :create
  skip_before_filter :verify_authenticity_token, only: :create

  def add_cookie_acceptance
    response.set_cookie 'rack.policy', {
      value: 'true',
      path: '/',
      expires: 1.year.from_now.utc
    }
  end

  private :add_cookie_acceptance
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  before_filter :add_cookie_acceptance, only: :create
  skip_before_filter :verify_authenticity_token, only: :create

  def add_cookie_acceptance
    response.set_cookie 'rack.policy', {
      value: 'true',
      path: '/',
      expires: 1.year.from_now.utc
    }
  end

  private :add_cookie_acceptance

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def show

  end

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/show.html.erb
<div class="row-fluid">
  <div class="span6 offset3 well">
    <h2>Upcoming Shows</h2>
    <%= link_to "View all shows", shows_path, class: "btn btn-info" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
<meta charset="utf-8">

<!-- Use the .htaccess and remove these lines to avoid edge case issues.
  More info: h5bp.com/i/378 -->
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<title>Hamsters Online</title>
<meta name="description" content="Online entries for hamster shows">

<!-- Mobile viewport optimized: h5bp.com/viewport -->
<meta name="viewport" content="width=device-width">

<!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

<%= stylesheet_link_tag "application" %>
<%= csrf_meta_tags %>

<!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

<!-- All JavaScript at the bottom, except this Modernizr build.
  Modernizr enables HTML5 elements & feature detects for optimal performance.
  Create your own custom Modernizr build: www.modernizr.com/download/ -->
<%= javascript_include_tag 'modernizr' %>

<!-- Initializes the modernizr and actually perform the checks. Enable this
if you need the modernizr, but remember to only do the actual checks
  that you need. -->
  <%= javascript_tag "Modernizr.load();" %>
</head>
<body>
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
  chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

  <!-- Add your site or application content here -->
  <div class="container-fluid">
    <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </div>


  <!-- JavaScript at the bottom for fast page loading: http://developer.yahoo.com/performance/rules.html#js_bottom -->
  <%= javascript_include_tag 'application' %>

  <% if Rails.env.production? %>
    <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
    mathiasbynens.be/notes/async-analytics-snippet -->
    <script>
      var _gaq=[['_setAccount','UA-10792414-3'],['_trackPageview']];
      (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g,s)}(document,'script'));
    </script>
  <% end %>
</body>
</html>

app/views/shared/_footer.html.erb
<div class="navbar navbar-inverse footer">
  <div class="navbar-inner">
    <ul class="nav">
      <li><a href="#">Privacy</a></li>
      <li><a href="#">Cookies</a></li>
      <li><a href="#">Terms of Service</a></li>
    </ul>
    <div class="pull-right">
      <%= link_to root_path, class: "brand" do %>
        &copy; 2013, David Workman
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse header">
  <div class="navbar-inner">
    <%= link_to "Hamsters Online", root_path, class: "brand" %>
    <ul class="nav">
      <li class="dropdown">
      <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
        Clubs
        <span class="caret"></span>
      <% end %>
      <ul class="dropdown-menu">
        <li class="nav-header">Your clubs</li>
      </ul>
      </li>
      <li class="dropdown">
      <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
        Shows
        <span class="caret"></span>
      <% end %>
      <ul class="dropdown-menu">
        <li class="nav-header">Your Shows</li>
      </ul>
      </li>
    </ul>
    <ul class="pull-right nav">
      <% if current_user %>
        <li class="dropdown">
        <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
          <%= current_user.email %>
          <span class="caret"></span>
        <% end %>
        <ul class="dropdown-menu">
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        </ul>
        </li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
      <%end%>
    </ul>
  </div>
</div>

app/views/shows/index.html.erb
<div class="row-fluid">
  <div class="span6 well">
    <h2>Upcoming Shows</h2>
  </div>
  <div class="span6 well">
    <h2>Previous Shows</h2>
  </div>
</div>

app/views/shows/show.html.erb
<div class="row-fluid">
</div>